---
title: "时间序列分析引论作业"
author: "Phlinsia"
date: "2024-03-14"
CJKmainfont: SimSun
output:
  pdf_document:
    includes:
        header-includes:
          - \usepackage{xeCJK}
        keep_tex: yes
    latex_engine: xelatex
---

```{r setup, echo=FALSE,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=8, fig.height=4)
library(showtext)
font_families()
showtext_auto()
```

## 1.1.Larain时间序列图

```{r 1.1, echo=T}
library(TSA)
library(latticeExtra)
data(larain, package = "TSA")
xyplot(larain, ylab = "英尺", xlab = "年", type = "o")
```


## 1.2.Color时间序列图

```{r 1.2, echo=T}
data(color)
xyplot(color, ylab = "颜色属性", xlab = "批次", type = "o")
```

## 1.3.随机独立正态分布

```{r 1.3, echo=T}
xyplot(as.ts(rnorm(48)))
xyplot(as.ts(rnorm(48)))
```
基本随机，看不出什么模式。

## 1.4.随机$\gamma^2$分布时间序列

```{r 1.4, echo=T}
xyplot(as.ts(rchisq(48, 2)))
xyplot(as.ts(rchisq(48, 2)))
```
结果随机，同时符合非正态性。

## 1.5.随机值$t(5)$分布

```{r 1.5.1, echo=T}
xyplot(as.ts(rt(48, 5)))
```

```{r 1.5.2, echo=T}
xyplot(as.ts(rt(48, 5)))
```

结果随机，同时符合非正态性。

## 1.6.迪比克市气温序列（月度标识）

```{r 1.5, echo=T}
data(tempdub)
xyplot(tempdub ~ time(tempdub), type = 'l', ylab = '温度', xlab = '年份',
       panel = function(x, y, ...) {
           panel.xyplot(x, y, ...)
           panel.points(x, y, pch = as.vector(season(tempdub)))
       })
```
